### ISSUE TITLE
Include on the cloud design the fact that a project could have multiple URLs

### ISSUE THREAD

**Issue by qdequele** [meilisearch/design-team#24]
# Context
The complete context is on the Tracking Issue https://github.com/meilisearch/product/issues/399
for now 2 urls: the old one and the new
then users could eventually have more

[Final mockups](https://www.figma.com/file/9GA8LomQgcbKiozYhgxa0C/Cloud-Interfaces?node-id=2523%3A4166)

# Todo
- [ ]

**Comment by chayaline** [comment]
Here is a proposition for the project details. I think we can only display the new one on the project list for now
[Figma exploration](https://www.figma.com/file/9GA8LomQgcbKiozYhgxa0C/SaaS-Interfaces?node-id=2673%3A5035)

**Comment by chayaline** [comment]
Project overview > Project overview
![Capture d’écran 2022-03-02 à 15 16 57](https://user-images.githubusercontent.com/16258667/156378941-0088a5f8-0dad-4a60-81ce-3e40415bdc92.png)

Dashboard
![Capture d’écran 2022-03-02 à 14 27 30](https://user-images.githubusercontent.com/16258667/156370674-14804069-c7db-453b-b0db-7afd8d287b49.png)
