### ISSUE TITLE
Design the movies demo

### ISSUE THREAD

**Issue by qdequele** [meilisearch/design-team#3]
## Todo

- [x]  Wireframming
- [x]  Page placeholder
- [x]  Fiche Film
- [x]  Fiche TV-Show
- [x]  Fiche People
- [x]  Mobile
- [ ]  Version Blanche
- [ ]  Animations?

# Figma

[https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FwUUkpIROZ0r89FxAy3ttLU%2Fwireframes-movies-demo%3Fnode-id%3D0%253A1](https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FwUUkpIROZ0r89FxAy3ttLU%2Fwireframes-movies-demo%3Fnode-id%3D0%253A1)

[https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FwUUkpIROZ0r89FxAy3ttLU%2Fwireframes-movies-demo%3Fnode-id%3D66%253A164](https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FwUUkpIROZ0r89FxAy3ttLU%2Fwireframes-movies-demo%3Fnode-id%3D66%253A164)

[https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FwUUkpIROZ0r89FxAy3ttLU%2Fwireframes-movies-demo%3Fnode-id%3D155%253A146](https://www.figma.com/embed?embed_host=notion&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FwUUkpIROZ0r89FxAy3ttLU%2Fwireframes-movies-demo%3Fnode-id%3D155%253A146)

**Comment by lpinot** [comment]
test
