### ISSUE TITLE
Help center: changes before release

### ISSUE THREAD

**Issue by chayaline** [meilisearch/design-team#35]
- [x] remove FAQ
- [x] remove the stickers button
- [x] add button for the helpcenter
- [x] maybe an illustration?

# resource
- [Figma mockup](https://www.figma.com/file/oIbwwEPhlIV1Pt1kCvEWBD/Help-center?node-id=313%3A225)

**Comment by qdequele** [comment]
@chayaline do you think we can close this issue. After a discussion with @lpinot it seems that it's finished since a while.

**Comment by chayaline** [comment]
For me it's not finished: we changed the buttons some icons might be changed and it's missing an illustration to replace the FAQ that needed to be removed.
Unless the requirements changed and those are not needed anymore?

**Comment by chayaline** [comment]
done!

![Image](https://user-images.githubusercontent.com/16258667/173824829-8948f4bc-3aa4-46ba-ae96-376f968e5d3a.png)
