### ISSUE TITLE
UI design for the responsive pricing helper quizz

### ISSUE THREAD

**Issue by lpinot** [meilisearch/design-team#42]
## Description
Create a block on the pricing page that will help users to choose the right plan on the cloud. This quick is like a form with the following questions:
- What is your use case?
- How many searches per month do you have?
- What feature are you interested in?
- How many documents do you have?
- What is the total size of your documents?
- What update frequency do you need?

At the end, the goal is to show the user the plan that fits perfectly to its needs or to tell him to contact a salesperson. 

## Ressource

https://www.figma.com/file/nIpVrmcFiW5LuaBhZBPxOT/Pricing?node-id=209%3A10623

## Steps
- [x] Create a wireframe representing the different choices
- [x] Design the desktop version 
- [x] Design the mobile and tablet version

**Comment by qdequele** [comment]
@lpinot I've updated it a little bit the issue to give you a sense of what I imagine to be a well-written task.
