### ISSUE TITLE
UI for the cloud onboarding

### ISSUE THREAD

**Issue by lpinot** [meilisearch/design-team#47]

**Comment by lpinot** [comment]
## Description

I need to transform the wireframes of the onboarding into user interfaces.
These interfaces include

- [x] Dashboard with a "create a project" CTA
- [x] The project creation form
- [x] The index creation form
- [ ] Waiting for approval

## Ressource

https://www.figma.com/file/Vm4K0vMp74z7oly7IL3POu/Onboarding?node-id=101%3A23

**Comment by chayaline** [comment]
Je pense que tu peux fermer cette issue ✅
